# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa7f4ead9c8e980b82c060fa41c4cbd07ce0a6f49af3032d964da087f797709b5eca48087c958dbd6ebc85c58d21d3cf1e1ac48a98ca0e49c900a3c8d711dcf3

test:
  secret_key_base: c8dfce660c1ac5f42d67a8d6e39c82674a15557e3791ca8e463b7b2740a7f0f685ac416ffff06f58bfa42666d99a9bc802eeba09a483eb099c2275df5484daae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
